#!/usr/bin/env bash
if [ "$2" == "clone" ]; then
  git clone https://github.com/clean-docker/Magento2.git $1 && cd $1;
fi

sudo chmod u+x ./*

if [ "$(uname)" == "Darwin" ]; then
  git checkout mac;
  sed -i '' -e "s/<project_name>/$1/g" docker-compose.yml \
  && sed -i '' -e "s/<project_name>/$1/g" docker-compose-dev.yml \
  && sed -i '' -e "s/<project_name>/$1/g" docker-sync.yml
else
  git checkout master;
  sed -i '' -e "s/<project_name>/$1/g" docker-compose.yml;
fi

bash start
