#!/usr/bin/env bash

if [ "$(uname)" == "Darwin" ]; then
  sed -i '' -e "s/<project_name>/$1/g" docker-compose.yml \
  && sed -i '' -e "s/<project_name>/$1/g" docker-compose-dev.yml \
  && sed -i '' -e "s/<project_name>/$1/g" docker-sync.yml
else
  sed -i '' -e "s/<project_name>/$1/g" docker-compose.yml
fi

echo '=================== Done =================='
