#!/usr/bin/env bash
docker-compose up -d && \
version=$(git tag)
echo "
===================== 🚀 Done 🚀 ===================

      Created by Rafael Corrêa Gomes
      v.$version
      Access your new links:

      🌎 Web server: http://localhost/
      ⚙️ PHPMyAdmin: http://localhost:8080
      ✉️ Local emails: http://localhost:8025

===================== 🚀 Done 🚀 ==================="
